version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: clientedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./BaseDatos.sql:/docker-entrypoint-initdb.d/BaseDatos.sql
    networks:
      - backend

  cliente-service:
    build:
      context: ./cliente-service
    container_name: cliente-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/clientedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - backend

  movimiento-service:
    build:
      context: ./movimiento-service
    container_name: movimiento-service
    ports:
      - "8081:8081"
    depends_on:
      - cliente-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/clientedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - CLIENTE_SERVICE_URL=http://cliente-service:8080/api/clientes
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge